Add Xilinx BSCANE2 tap
pulp-platform/riscv-dbg pull request #111
Opened 2021-04-25 18:19 UTC by zarubaf

Alternative tap implementation for Xilinx devices which are not easily
accessible by means of a dedicated JTAG header. This implementation
should also be portable amongst 7-series and Ultrascale+ devices.

The commit also contains a testbench for the regular JTAG TAP and the
BSCANE2 TAP (same testbnech really). Both testbenches pass and hopefully
give confidence that I didn't introduce a regression.

2021-04-25 18:23 UTC, zarubaf commented
It should be said that I didn't test the implementation yet on the FPGA board for functionality, it works in simulation though (simulating the Xilinx primitives using Questa). 

Also referencing https://github.com/lowRISC/opentitan/issues/72 since it might be interesting (and/or you could be an early adopter :-)).

2021-04-25 18:31 UTC, zarubaf commented
@niwis That is also potentially the solution to have the VCU128 accessible without using a Zynq or instantiating a uBlaze.

2021-04-27 12:48 UTC, zarubaf commented
@stefanct confirmed that the `BSCANE2` TAP works on his Zedboard. As the OpenOCD configuration isn't 100% trivial I've added some more words to the documentation. From my side, this is ready to be looked at.

2021-05-24 11:58 UTC, zarubaf commented
Ping @bluewww Let me know if there is a problem with merging this.

2021-05-25 13:35 UTC, bluewww requested changes
Useful feature!
Generally looks ok to me except for a few nits.

I'll pipe this through PULPissimo CI to see if anything major turns up then it should be good to go.

2021-05-25 13:35 UTC, bluewww commented on .gitignore
> +Bender.lock
Terminating newline missing

2021-05-25 13:35 UTC, bluewww commented on src/dmi_intf.sv
> +// The DV interface additionally caries a clock signal.
carries

2021-05-25 13:35 UTC, bluewww commented on src/dmi_jtag.sv
> +  // signal.
Whats the state of this TODO?

2021-05-25 13:35 UTC, bluewww commented on tb/jtag_dmi/.gitignore
> +work/
Missing terminating newline

2021-05-25 13:59 UTC, zarubaf commented
Thanks, I've addressed the nits.

2021-05-26 13:33 UTC, imphil reviewed
This looks great! Sorry for not jumping in earlier, but I have some smallish comments about the docs.

2021-05-26 13:33 UTC, imphil commented on doc/jtag_dmi.md
> +# JTAG Debug Module Interface
DMI is the interface, DTM is the transport itself. The code is already rather confused/wrong about this, let's not make it worse :smile: 

```suggestion
# JTAG Debug Transport Module
```


A more general comment: I would (prefer) including this documentation in the debug-system.md file to have it all in one place.

2021-05-26 13:33 UTC, imphil commented on doc/jtag_dmi.md
> +The JTAG DMI takes care of translating JTAG signals into the custom DMI protocol
```suggestion
The JTAG DTM takes care of translating JTAG signals into the custom DMI protocol
```

2021-05-26 13:54 UTC, zarubaf commented on src/dmi_jtag.sv
> +  // signal.
The same as before. I think it is a separate issue that is already open here. If somebody finds the time to implement and verify it that would be nice - but nothing fundamentally new about this that was introduced here.

2021-05-26 13:55 UTC, zarubaf commented
Thanks, @imphil - addressed our concerns.

2021-05-30 16:47 UTC, merged

2021-07-08 06:19 UTC, stefanct commented
I am currently trying to get this to work (with the same pulpissimo version that worked on the zedboard) on a ZCU102 board containing an xczu9eg but fail. I tried to understand how Florian had come up with all the values and found the BSDL models. I have added a bunch of devices but I did not check both tables completely (somebody summer intern should build a script for that ;)

Nevertheless, I have found quite some inconsistencies and came to the conclusion that either I don't understand it completely, Florian made some errors, or both :)
The resulting docs update is here (I can make a pull request later if you like):
https://github.com/pulp-platform/riscv-dbg/commit/553db20ff9df03fb31998171ddf841b4a28103fe

My question is rather... why doesn't it work on the xczu9eg? I get:

Error: 293 13 riscv-013.c:1486 examine(): Debug Module did not become active. dmcontrol=0x0

The following is my oocd config, the `-d4` log is [attached](https://github.com/pulp-platform/riscv-dbg/files/6782001/oocd.txt). I also tried the other values for IR length == 12 to no avail. Maybe the ftdi config is not correct? But it reads the IDs correctly...

    interface ftdi
    transport select jtag

    ftdi_vid_pid 0x0403 0x6014

    ftdi_layout_init 0x00e8 0x60eb
    #ftdi_tdo_sample_edge falling doesnt matter
    reset_config none

    # just to avoid a warning about the auto-detected arm core
    jtag newtap arm_unused tap -irlen 4 -expected-id 0x5ba00477

    set _CHIPNAME riscv
    jtag newtap $_CHIPNAME cpu -irlen 12 -expected-id 0x24738093

    set _TARGETNAME $_CHIPNAME.cpu
    target create $_TARGETNAME riscv -chain-position $_TARGETNAME -coreid 0x3e0

    riscv set_ir idcode 0x249
    riscv set_ir dtmcs 0x922
    riscv set_ir dmi 0x923

    adapter_khz     1000